version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-50-19-221-38.compute-1.amazonaws.com
            port: '5432'
            database: d1rt9qeko905at
            # schema: schema.graphql
            ssl: true
            user: mdzfrfwcjizfgz
            password: e9e2545fd8c148b7b516012c81138d6ef5d7d1bed308ac9387a0421d1eb2d579
            migrations: true